#!/bin/bash

if [ $# -eq 0 ]; then
    RUBY_VERSION=2.6.3
else
    RUBY_VERSION=$1
fi

set -e

docker build --build-arg ruby_version=$RUBY_VERSION -f docker/Dockerfile -t edn_turbo_image:rb-$RUBY_VERSION .
