#!/bin/bash

if [ $# -eq 0 ]; then
    RUBY_VERSION=2.7.0
else
    RUBY_VERSION=$1
fi

set -e

docker build --build-arg ruby_version=$RUBY_VERSION -f docker/Dockerfile -t digressed/test:edn_turbo-rb-$RUBY_VERSION .
