#!/bin/bash

if [ $# -eq 0 ]; then
    RUBY_VERSION=3.0.0
else
    RUBY_VERSION=$1
fi

echo "running on ruby ${RUBY_VERSION}"

docker-compose -f docker/docker-compose.yml run rb-$RUBY_VERSION /bin/bash
